all: stack stdin out-parameter punning array

stack: example-stack.c
	gcc example-stack.c -o example-stack.bin

stdin: example-stdin.c
	gcc example-stdin.c -o example-stdin.bin

out-parameter: example-output-parameter.c
	gcc example-output-parameter.c -o example-output-parameter.bin

punning: example-punning.c
	gcc example-punning.c -o example-punning.bin

array: example-array.c
	gcc example-array.c -o example-array.bin
